apiVersion: v1
kind: Service
metadata:
  name: adminer-web
spec:
  ports:
    - port: 8082
      targetPort: 8080
  selector:
    app: adminer-web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-web
spec:
  selector:
    matchLabels:
      app: adminer-web
  template:
    metadata:
      labels:
        app: adminer-web
    spec:
      containers:
        - name: web
          image: adminer:4.7-standalone
          env:
            - name: ADMINER_DEFAULT_SERVER_FILE
              value: /secrets/default-server
            - name: ADMINER_DESIGN
              valueFrom:
                configMapKeyRef:
                  name: adminer-config
                  key: ADMINER_DESIGN
          volumeMounts:
            - name: secret
              mountPath: "/secrets"
          args: ["php", "-S", "0.0.0.0:8080", "-t", "/var/www/html"]

      volumes:
        - name: secret
          secret:
            secretName: ch04-adminer-default-server-secret
            defaultMode: 0400
            items:
              - key: ADMINER_DEFAULT_SERVER
                path: default-server